### ISSUE TITLE
crn_decomp.h(598): Assertion failure: "i < m_size" on crn files created with Unity 5

### ISSUE THREAD

**Issue by suphamster** [DaemonEngine/crunch#24]
[crn.zip](https://github.com/DaemonEngine/crunch/files/8827196/crn.zip)
I've attached crn file and very old version of crunch tool that allows to unpack (crn2dds) such file but it's useless for new version of Unity so plz add such files support in current version if possible.

**Comment by slipher** [comment]
A few years ago Unity open-sourced a version of Crunch with a redesigned file format with better efficiency. Daemon engine adopted these changes. The new Unity file format/tools are mutually incompatible with the original ones from Binomial (which Unity 5 presumably uses since it predates the new format).

You might be able to unpack older files by checking out e.g. the `upstream/binomial` branch.

**Comment by illwieckz** [comment]
Hi, it looks like the provided file is using the old CRN format by Binomial, as I verified I could convert the CRN file to PNG using old Binomial crunch tool.

Unfortunately when Unity improved the crunch tool it breaks the compatibility with old Binomial format, and I doubt they put some ways to identify the versions, so this is very unlikely a single tool can read both easily (and without the user telling what format it is).

What you can do is to use two versions of crunch, rename the old one with another name (like `crunch.binormal`).

So you can do:

```
crunch.binomial file.crn -out file.png
crunch file.png -out file.crn
```

Unfortunately this will not provide a 1:1 copy (but good enough) because it would be lossy compressed a second time. We did that for our game with a couple of old files we didn't have png source for.

Note that if some of the original crunch files were using specific storage formats (like when using the `-dxn` option), you may want to use the same option to reduce the risk of losing some bits of information.

**Comment by illwieckz** [comment]
I just verified that your old `crunch.exe` is the old binary that was shipped within old crunch repository at google code by Binomial (committed 2012-11-25), they share the exact same checksum.

So you may rename it to `crunch-binomial.exe` and convert all your old crn files to png, then convert all those png to crn again using a new build of crunch.
